In [1]:
from tensorflow.keras.preprocessing.text import one_hot

In [2]:
sent = ["the glass of milk",
       "the glass of juice",
        "the mug of coffee",
        "I am a developer",
        "I build things",
        "I understand things"]

In [3]:
sent

['the glass of milk',
 'the glass of juice',
 'the mug of coffee',
 'I am a developer',
 'I build things',
 'I understand things']

In [4]:
vocab_size = 10000

In [5]:
one_hot_rep =[one_hot(words,vocab_size)for words in sent]
print(one_hot_rep)

[[9601, 4232, 7712, 6035], [9601, 4232, 7712, 3637], [9601, 1207, 7712, 6853], [6155, 6309, 9170, 9512], [6155, 3953, 2681], [6155, 3336, 2681]]


In [6]:
### Word Embeddings ###
from tensorflow.keras.layers import Embedding
from tensorflow.keras.models import Sequential
from tensorflow.keras.preprocessing.sequence import pad_sequences

In [7]:
import numpy as np
sent_length = 8

In [8]:
embed_layer = pad_sequences(one_hot_rep, padding = 'pre', maxlen = sent_length)
print(embed_layer)

[[   0    0    0    0 9601 4232 7712 6035]
 [   0    0    0    0 9601 4232 7712 3637]
 [   0    0    0    0 9601 1207 7712 6853]
 [   0    0    0    0 6155 6309 9170 9512]
 [   0    0    0    0    0 6155 3953 2681]
 [   0    0    0    0    0 6155 3336 2681]]


In [9]:
dims = 15

In [11]:
model = Sequential()
model.add(Embedding(vocab_size,15,input_length=sent_length))
model.compile('adam','mse')

In [12]:
model.summary()

Model: "sequential_1"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding_1 (Embedding)      (None, 8, 15)             150000    
Total params: 150,000
Trainable params: 150,000
Non-trainable params: 0
_________________________________________________________________


In [13]:
print(model.predict(embed_layer))

[[[ 0.01901997 -0.03241121  0.01957445  0.00395133  0.04816483
   -0.00171721 -0.03647913  0.04565888  0.01449085 -0.02918433
   -0.00467644  0.01828662  0.02048907  0.0249502  -0.01286521]
  [ 0.01901997 -0.03241121  0.01957445  0.00395133  0.04816483
   -0.00171721 -0.03647913  0.04565888  0.01449085 -0.02918433
   -0.00467644  0.01828662  0.02048907  0.0249502  -0.01286521]
  [ 0.01901997 -0.03241121  0.01957445  0.00395133  0.04816483
   -0.00171721 -0.03647913  0.04565888  0.01449085 -0.02918433
   -0.00467644  0.01828662  0.02048907  0.0249502  -0.01286521]
  [ 0.01901997 -0.03241121  0.01957445  0.00395133  0.04816483
   -0.00171721 -0.03647913  0.04565888  0.01449085 -0.02918433
   -0.00467644  0.01828662  0.02048907  0.0249502  -0.01286521]
  [-0.00744829 -0.03821586  0.04315749  0.03050404 -0.04881537
    0.02968098  0.04334427  0.0486945   0.02742459 -0.04287968
   -0.00114055  0.02564505 -0.04049785  0.01250932 -0.00508021]
  [-0.00140868 -0.00935589  0.04008602  0.01721806